name: CI
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11
      - name: Setup sbt launcher
        uses: sbt/setup-sbt@v1
      - name: Build and Test
        env:
          DEVELOCITY_ACCESS_KEY: "${{ secrets.DEVELOCITY_ACCESS_KEY }}"
        run: sbt -Ddevelocity.internal.cache.verbose=true -Ddevelocity.internal.cache.defaultLogLevel=info clean compile test
      - name: List cache content
        run: ls -la /tmp/develocity-cache
      - name: Create cache archive
        run: tar czf develocity-cache.tar.gz -C /tmp/develocity-cache
      - name: List of the GitHub Actions environment variables
        run: env
      - name: Upload cache archive
        uses: actions/upload-artifact@v4
        with:
          name: cache-archive-${{ github.repository }}-${{ github.ref_name }}-${{ github.event.pull_request.number }}
          path: develocity-cache.tar.gz
        